version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend/integracao-colaboradores:/app
    ports:
      - "4200:4200"
    command: sh -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=integracao
      - DB_USERNAME=postgres
      - DB_PASSWORD=senha
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"



  db:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: integracao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
